name: ADF Deployment

on:
  push:
    branches:
      - adf_publish
  workflow_dispatch:
    inputs:
      skipAzModuleInstallation:
        description: 'Skip the installation of Az PowerShell module'
        required: false
        default: 'false'

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        stage: ['test']
      fail-fast: true
      max-parallel: 1
    environment:
      name: ${{ matrix.stage }}

    steps:
      # Step 1: Set Variables
      - name: Set Variables
        run: |
          echo "Setting up required environment variables"
          echo "RESOURCE_GROUP_NAME=test" >> $GITHUB_ENV
          echo "STG_ACCOUNT_NAME=adftempaltedeploy" >> $GITHUB_ENV
          echo "CONTAINER_NAME=templates" >> $GITHUB_ENV
          echo "FILE_PATH=./adf-github-actions/linkedTemplates/" >> $GITHUB_ENV

      # Step 2: Checkout Target Branch (adf_publish)
      - name: Checkout Target Branch (adf_publish)
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: adf_publish

      # Step 3: Fetch Scripts from Main Branch
      - name: Fetch Scripts from Main Branch
        run: |
          git fetch origin main
          mkdir -p temp
          git show origin/main:PrePostDeploymentScript.ps1 > temp/PrePostDeploymentScript.ps1
          git show origin/main:StgSASToken.ps1 > temp/StgSASToken.ps1
          git checkout adf_publish
          ls -l temp

      # Step 4: Install Az PowerShell Module Conditionally
      - name: Install Az PowerShell Module
        if: inputs.skipAzModuleInstallation != 'true'
        run: |
          Install-Module -Name Az -Scope CurrentUser -Repository PSGallery -Force
        shell: pwsh

      # Step 5: Azure Login
      - name: Azure Login
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          enable-AzPSSession: true

      # Step 6: Upload Linked Templates to Azure Storage
      - name: Upload Linked Templates to Azure Storage
        run: |
          echo "Uploading ARM templates to Azure Storage"
          az storage container create --name $CONTAINER_NAME --account-name $STG_ACCOUNT_NAME --auth-mode login
          for file in $FILE_PATH*.json; do
            az storage blob upload --account-name $STG_ACCOUNT_NAME --container-name $CONTAINER_NAME --file "$file" --name "$(basename $file)" --overwrite
          done

      # Step 7: Generate SAS Token
      - name: Generate SAS Token
        id: generate_sas
        shell: pwsh
        run: |
          Write-Host "Generating SAS Token"
          $sasDetails = ./temp/StgSASToken.ps1 -ResourceGroupName $env:RESOURCE_GROUP_NAME -StgAccName $env:STG_ACCOUNT_NAME
          $sasToken = $sasDetails -match "se=.*" | Out-String
          $sasToken = $sasToken.Trim()
          $templateBaseUrl = "https://${env:STG_ACCOUNT_NAME}.blob.core.windows.net/${env:CONTAINER_NAME}"

          Write-Host "SAS_TOKEN=$sasToken" | Out-File -FilePath $env:GITHUB_ENV -Append
          Write-Host "TEMPLATE_BASE_URL=$templateBaseUrl" | Out-File -FilePath $env:GITHUB_ENV -Append

      # Step 8: Debug Environment Variables
      - name: Debug Environment Variables
        run: |
          echo "TEMPLATE_BASE_URL=${{ env.TEMPLATE_BASE_URL }}"
          echo "SAS_TOKEN=${{ env.SAS_TOKEN }}"

      # Step 9: Run Pre-deployment Script
      - name: Run Pre-deployment Script
        shell: pwsh
        run: |
          pwsh -command "./temp/PrePostDeploymentScript.ps1 -armTemplate '${{ env.TEMPLATE_BASE_URL }}/ArmTemplate_master.json?${{ env.SAS_TOKEN }}' -ResourceGroupName ${{ env.RESOURCE_GROUP_NAME }} -DataFactoryName adf-github-actions-test -predeployment $true -deleteDeployment $false"

      # Step 10: Deploy ADF ARM Templates
      - name: Deploy ADF ARM Templates
        uses: Azure/arm-deploy@v1
        with:
          resourceGroupName: ${{ env.RESOURCE_GROUP_NAME }}
          template: ${{ env.TEMPLATE_BASE_URL }}/ArmTemplate_master.json?${{ env.SAS_TOKEN }}
          parameters: |
            factoryName=adf-github-actions-test
          deploymentMode: Incremental

      # Step 11: Run Post-deployment Script
      - name: Run Post-deployment Script
        shell: pwsh
        run: |
          pwsh -command "./temp/PrePostDeploymentScript.ps1 -armTemplate '${{ env.TEMPLATE_BASE_URL }}/ArmTemplate_master.json?${{ env.SAS_TOKEN }}' -ResourceGroupName ${{ env.RESOURCE_GROUP_NAME }} -DataFactoryName adf-github-actions-test -predeployment $false -deleteDeployment $true"