name: ADF Deployment

on:
  push:
    branches:
      - adf_publish
  workflow_dispatch:
    inputs:
      skipAzModuleInstallation:
        description: 'Skip the installation of Az PowerShell module'
        required: false
        default: 'false'

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        stage: ['test']
      fail-fast: true
      max-parallel: 1
    environment:
      name: ${{ matrix.stage }}

    steps:
      # Checkout the adf_publish branch
      - name: Checkout Target Branch
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: adf_publish

      # Fetch PrePostDeploymentScript.ps1 from main branch
      - name: Fetch and Copy Script from Main
        run: |
          # Fetch the main branch
          git fetch origin main
          
          # Check out the script to a temporary directory
          mkdir -p temp
          git show origin/main:PrePostDeploymentScript.ps1 > temp/PrePostDeploymentScript.ps1
          
          # Verify the script is copied
          echo "Copied script:"
          ls -l temp

      # Debugging step to list files in the workspace
      - name: Debug Directory Structure
        run: |
          echo "Current directory:"
          pwd
          echo "Listing files:"
          ls -R

      # Install Az PowerShell module conditionally
      - name: Install Az PowerShell module
        if: inputs.skipAzModuleInstallation != 'true'
        run: |
          Install-Module -Name Az -Scope CurrentUser -Repository PSGallery -Force
        shell: pwsh

      # Azure Login
      - name: Azure Login
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          enable-AzPSSession: true

      # Run Pre-deployment script
      - name: Run Pre-deployment script
        run: |
          pwsh -command "./temp/PrePostDeploymentScript.ps1 -armTemplate ./ARMTemplateForFactory.json -ResourceGroupName test -DataFactoryName adf-github-actions-test -predeployment $true -deleteDeployment $false"
        shell: pwsh

      # Deploy ADF ARM Templates
      - name: Deploy ADF ARM Templates
        uses: Azure/arm-deploy@v1
        with:
          resourceGroupName: ${{ vars.AZURE_RG }}
          template: ./ARMTemplateForFactory.json
          parameters: |
            factoryName=${{ vars.ADF_FACTORYNAME }}
            ADLS_properties_typeProperties_url=${{ vars.ADF_ADLS_PROPERTIES_TYPEPROPERTIES_URL }}
            AzureBlob_properties_typeProperties_serviceEndpoint=${{ vars.ADF_AZUREBLOB_PROPERTIES_TYPEPROPERTIES_SERVICEENDPOINT }}
            AzureKeyVault_properties_typeProperties_baseUrl=${{ vars.ADF_AZUREKEYVAULT_PROPERTIES_TYPEPROPERTIES_BASEURL }}

      # Run Post-deployment script
      - name: Run Post-deployment script
        run: |
          pwsh -command "./temp/PrePostDeploymentScript.ps1 -armTemplate ./ARMTemplateForFactory.json -ResourceGroupName test -DataFactoryName adf-github-actions-test -predeployment $false -deleteDeployment $true"
        shell: pwsh