name: ADF Deployment

on:
  push:
    branches:
      - adf_publish
  workflow_dispatch:
    inputs:
      skipAzModuleInstallation:
        description: 'Skip the installation of Az PowerShell module'
        required: false
        default: 'false'

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        stage: ['test']
      fail-fast: true
      max-parallel: 1
    environment:
      name: ${{ matrix.stage }}

    steps:
      # Step 1: Checkout Target Branch (adf_publish)
      - name: Checkout Target Branch (adf_publish)
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: adf_publish

      # Step 2: Fetch Scripts from Main Branch
      - name: Fetch Scripts from Main Branch
        run: |
          git fetch origin main
          mkdir -p temp
          git show origin/main:PrePostDeploymentScript.ps1 > temp/PrePostDeploymentScript.ps1
          git show origin/main:StgSASToken.ps1 > temp/StgSASToken.ps1
          git checkout adf_publish
          ls -l temp

      # Step 3: Install Az PowerShell Module Conditionally
      - name: Install Az PowerShell Module
        if: inputs.skipAzModuleInstallation != 'true'
        run: |
          Install-Module -Name Az -Scope CurrentUser -Repository PSGallery -Force
        shell: pwsh

      # Step 4: Azure Login
      - name: Azure Login
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          enable-AzPSSession: true

      # Step 5: Upload Linked Templates to Azure Storage
      - name: Upload Linked Templates to Azure Storage
        run: |
          echo "Uploading ARM templates to Azure Storage"
          az storage container create --name templates --account-name adftempaltedeploy --auth-mode login
          for file in ./adf-github-actions/linkedTemplates/*.json; do
            az storage blob upload --account-name adftempaltedeploy --container-name templates --file "$file" --name "$(basename $file)" --overwrite
          done

      # Step 6: Generate SAS Token
      - name: Generate SAS Token
        id: generate_sas
        shell: pwsh
        run: |
          Write-Host "Generating SAS Token"
          $sasDetails = ./temp/StgSASToken.ps1 -ResourceGroupName test -StgAccName adftempaltedeploy
          $sasToken = $sasDetails -match "se=.*" | Out-String
          $sasToken = $sasToken.Trim()
          $templateBaseUrl = "https://adftempaltedeploy.blob.core.windows.net/templates"

          echo "SAS_TOKEN=${sasToken}" 
          echo "TEMPLATE_BASE_URL=${templateBaseUrl}" 

      # Step 7: Debug Environment Variables
      - name: Debug Environment Variables
        run: |
          echo "TEMPLATE_BASE_URL=${{ env.TEMPLATE_BASE_URL }}"
          echo "SAS_TOKEN=${{ env.SAS_TOKEN }}"

      # Step 8: Run Pre-deployment Script
      - name: Run Pre-deployment Script
        shell: pwsh
        run: |
          pwsh -command "./temp/PrePostDeploymentScript.ps1 -armTemplate '${{ env.TEMPLATE_BASE_URL }}/ArmTemplate_master.json?${{ env.SAS_TOKEN }}' -ResourceGroupName test -DataFactoryName adf-github-actions-test -predeployment $true -deleteDeployment $false"

      # Step 9: Deploy ADF ARM Templates
      - name: Deploy ADF ARM Templates
        uses: Azure/arm-deploy@v1
        with:
          resourceGroupName: test
          template: ${{ env.TEMPLATE_BASE_URL }}/ArmTemplate_master.json?${{ env.SAS_TOKEN }}
          parameters: |
            factoryName=adf-github-actions-test
            linkedTemplateBaseUrl=${{ env.TEMPLATE_BASE_URL }}
            linkedTemplateSasToken=${{ env.SAS_TOKEN }}
          deploymentMode: Incremental

      # Step 10: Run Post-deployment Script
      - name: Run Post-deployment Script
        shell: pwsh
        run: |
          pwsh -command "./temp/PrePostDeploymentScript.ps1 -armTemplate '${{ env.TEMPLATE_BASE_URL }}/ArmTemplate_master.json?${{ env.SAS_TOKEN }}' -ResourceGroupName test -DataFactoryName adf-github-actions-test -predeployment $false -deleteDeployment $true" 