name: ADF Deployment

on:
  push:
    branches:
      - adf_publish
  workflow_dispatch:
    inputs:
      skipAzModuleInstallation:
        description: 'Skip the installation of Az PowerShell module'
        required: false
        default: 'false'

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        stage: ['test']
      fail-fast: true
      max-parallel: 1
    environment:
      name: ${{ matrix.stage }}

    steps:
      # Step 1: Checkout Target Branch
      - name: Checkout Target Branch (adf_publish)
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: adf_publish

      # Step 2: Fetch Scripts from Main Branch
      - name: Fetch Scripts from Main Branch
        run: |
          git fetch origin main
          mkdir -p temp
          git show origin/main:PrePostDeploymentScript.ps1 > temp/PrePostDeploymentScript.ps1
          git show origin/main:StgSASToken.ps1 > temp/StgSASToken.ps1
          git checkout adf_publish
          ls -l temp

      # Step 3: Install Az PowerShell Module Conditionally
      - name: Install Az PowerShell Module
        if: ${{ inputs.skipAzModuleInstallation != 'true' }}
        run: |
          Install-Module -Name Az -Scope CurrentUser -Repository PSGallery -Force
        shell: pwsh

      # Step 4: Azure Login
      - name: Azure Login
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          enable-AzPSSession: true

      # Step 5: Upload Linked Templates to Azure Storage
      - name: Upload Linked Templates to Azure Storage
        run: |
          echo "Uploading ARM templates to Azure Storage"
          az storage container create --name templates --account-name adftempaltedeploy --auth-mode login
          for file in ./adf-github-actions/linkedTemplates/*.json; do
            az storage blob upload --account-name adftempaltedeploy --container-name templates --file "$file" --name "$(basename "$file")" --overwrite
          done
        shell: bash

      # Step 6: Generate SAS Token and Container URI
      - name: Generate SAS Token and Container URI
        id: generate_sas
        shell: pwsh
        run: |
          try {
            $ctx = (Get-AzStorageAccount -ResourceGroupName test -AccountName adftempaltedeploy).Context
            $StartTime = Get-Date
            $EndTime = $StartTime.AddHours(1)

            Write-Host "Start Time: $StartTime"
            Write-Host "End Time: $EndTime"

            $containerSasToken = New-AzStorageAccountSASToken -Context $ctx -Service Blob -ResourceType Service,Container,Object -Permission "racwdlup" -Protocol "HttpsOnly" -StartTime $StartTime -ExpiryTime $EndTime
            $containerUri = "https://adftempaltedeploy.blob.core.windows.net/templates"

            if (-not $containerSasToken) {
              Write-Error "Failed to generate SAS Token!"
              exit 1
            }

            if (-not $containerUri) {
              Write-Error "Failed to construct Container URI!"
              exit 1
            }

            Write-Host "Generated SAS Token: $containerSasToken"
            Write-Host "Container URI: $containerUri"

            # Export the SAS Token and Container URI to GitHub Environment Variables
            echo "containerSasToken=$containerSasToken" >> $GITHUB_ENV
            echo "containerUri=$containerUri"  >> $GITHUB_ENV
          } catch {
            Write-Error "Error occurred during SAS Token generation: $_"
            exit 1
          }

      # Step 7: Debug Environment Variables
      - name: Debug Environment Variables
        run: |
          echo "Container URI: ${{ env.containerUri }}"
          echo "Container SAS Token: ${{ env.containerSasToken }}"
        shell: bash

      # Step 8: Validate Environment Variables
      - name: Validate Environment Variables
        run: |
          if [ -z "${{ env.containerUri }}" ]; then
            echo "Error: containerUri is not set."
            exit 1
          fi

          if [ -z "${{ env.containerSasToken }}" ]; then
            echo "Error: containerSasToken is not set."
            exit 1
          fi
        shell: bash

      # Step 9: Deploy ADF ARM Templates
      - name: Deploy ADF ARM Templates
        uses: Azure/arm-deploy@v1
        with:
          resourceGroupName: test
          template: ${{ env.containerUri }}/ArmTemplate_master.json?${{ env.containerSasToken }}
          parameters: |
            {
              "factoryName": {
                "value": "adf-github-actions-test"
              },
              "containerUri": {
                "value": "${{ env.containerUri }}"
              },
              "containerSasToken": {
                "value": "?${{ env.containerSasToken }}"
              }
            }
          deploymentMode: Incremental
          failOnStdErr: true

      # Step 10: Run Post-deployment Script
      - name: Run Post-deployment Script
        shell: pwsh
        run: |
          ./temp/PrePostDeploymentScript.ps1 -armTemplate "${{ env.containerUri }}/ArmTemplate_master.json?${{ env.containerSasToken }}" -ResourceGroupName test -DataFactoryName adf-github-actions-test -predeployment $false -deleteDeployment $true