name: Deploy to Azure

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Log in to Azure
    - name: Azure Login
      uses: azure/login@v1
      with:
        client-id: 952fad4a-a77f-449a-9e1a-677324992633   # Replace with your App's Client ID
        tenant-id: 42f91328-1147-483c-99ed-e33d376b3ce2>       # Replace with your Tenant ID
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
