name: Deploy to Azure

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Log in to Azure
    - name: Azure Login
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}  # Replace with your GitHub secret
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}  # Replace with your GitHub secret
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}  # Ensure this is provided
