name: Deploy to Azure

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Log in to Azure
    - name: Azure Login
      uses: azure/login@v1
      with:
        client-id: <APP_CLIENT_ID>   # Replace with your App's Client ID
        tenant-id: <TENANT_ID>       # Replace with your Tenant ID
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
