name: Deploy to Azure

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Log in to Azure using creds
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    # Step 3: Checkout the adf_publish branch
    - name: Checkout ADF Publish Branch
      uses: actions/checkout@v3
      with:
        ref: adf_publish  # Explicitly check out the adf_publish branch

    # Step 2: Debug to list files
    - name: List files in the workspace
      run: ls -R

    # Step 3: Deploy ARM Templates
    - name: Deploy ARM Templates
      run: |
        az deployment group create \
          --resource-group my-resource-group \
          --template-file adf-github-actions/ARMTemplateForFactory.json \
          --parameters adf-github-actions/ARMTemplateParametersForFactory.json
