name: Deploy Data Factory with Pre/Post Deployment

on:
  push:
    branches:
      - main

env:
  resourceGroupName: 'test'
  dataFactoryName: 'adf-github-actions'
  armTemplateFile: 'ARMTemplateForFactory.json'
  armTemplateParametersFile: 'ARMTemplateParametersForFactory.json'
  additionalParameters: ''
  skipAzModuleInstallation: 'false'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout ADF Publish Branch
      uses: actions/checkout@v3
      with:
        ref: adf_publish

    - name: Install Az PowerShell Module
      run: |
        if('${{ env.skipAzModuleInstallation }}' -ne 'true') { 
          Install-Module -Name Az -Scope CurrentUser -Repository PSGallery -Force 
        }
      shell: pwsh

    - name: Run Pre-deployment script
      run: |
        ./adf-github-actions/PrePostDeploymentScript.ps1 `
          -armTemplate "adf-github-actions/${{ env.armTemplateFile }}" `
          -ResourceGroupName "${{ env.resourceGroupName }}" `
          -DataFactoryName "${{ env.dataFactoryName }}" `
          -predeployment $true `
          -deleteDeployment $false
      shell: pwsh

    - name: Deploy ARM Templates
      uses: azure/arm-deploy@v1
      with:
        resourceGroupName: ${{ env.resourceGroupName }}
        template: adf-github-actions/${{ env.armTemplateFile }}
        parameters: adf-github-actions/${{ env.armTemplateParametersFile }} factoryName=${{ env.dataFactoryName }} ${{ env.additionalParameters }}

    - name: Run Post-deployment script
      run: |
        ./adf-github-actions/PrePostDeploymentScript.ps1 `
          -armTemplate "adf-github-actions/${{ env.armTemplateFile }}" `
          -ResourceGroupName "${{ env.resourceGroupName }}" `
          -DataFactoryName "${{ env.dataFactoryName }}" `
          -predeployment $false `
          -deleteDeployment $true
      shell: pwsh