name: Deploy Data Factory with Pre/Post Deployment

on:
  push:
    branches:
      - main

env:
  resourceGroupName: 'test'
  dataFactoryName: 'adf-github-actions'
  armTemplateFile: 'ARMTemplateForFactory.json'
  armTemplateParametersFile: 'ARMTemplateParametersForFactory.json'
  additionalParameters: ''
  skipAzModuleInstallation: 'false'

jobs:
  deploy:
    runs-on: 'composite'

    steps:
    # Step 1: Checkout main branch for the script
    - name: Checkout main branch
      uses: actions/checkout@v3
      with:
        ref: main

    # Step 2: Copy the PrePostDeploymentScript.ps1 to a temp location
    - name: Copy PrePostDeploymentScript.ps1
      run: cp PrePostDeploymentScript.ps1 /tmp/PrePostDeploymentScript.ps1

    # Step 3: Checkout adf_publish branch for the ARM templates
    - name: Checkout adf_publish branch
      uses: actions/checkout@v3
      with:
        ref: adf_publish

    # Step 4: Debug - List all files
    - name: Debug - List all files
      run: ls -R

    # Step 5: Make the PrePostDeploymentScript.ps1 executable
    - name: Make script executable
      run: chmod +x /tmp/PrePostDeploymentScript.ps1

    # Step 6: Install Az PowerShell Module
    - name: Install Az PowerShell Module
      run: |
        if('${{ env.skipAzModuleInstallation }}' -ne 'true') { 
          Install-Module -Name Az -Scope CurrentUser -Repository PSGallery -Force 
        }
      shell: pwsh

    # Step 7: Run Pre-deployment script
    - name: Run Pre-deployment Script
      run: |
        pwsh /tmp/PrePostDeploymentScript.ps1 `
          -armTemplate "${{ env.armTemplateFile }}" `
          -ResourceGroupName "${{ env.resourceGroupName }}" `
          -DataFactoryName "${{ env.factoryName }}" `
          -predeployment $True `
          -deleteDeployment $False
      shell: pwsh

    # Step 8: Deploy ARM Templates
    - name: Deploy ARM Templates
      uses: azure/arm-deploy@v1
      with:
        resourceGroupName: ${{ env.resourceGroupName }}
        template: adf-github-actions/${{ env.armTemplateFile }}
        parameters: adf-github-actions/${{ env.armTemplateParametersFile }} factoryName=${{ env.dataFactoryName }} ${{ env.additionalParameters }}

    # Step 9: Run Post-deployment script
    - name: Run Pre-deployment script
      run: |
        pwsh -Command "& { ./tmp/PrePostDeploymentScript.ps1 `
          -armTemplate 'adf-github-actions/${{ env.armTemplateFile }}' `
          -ResourceGroupName '${{ env.resourceGroupName }}' `
          -DataFactoryName '${{ env.dataFactoryName }}' `
          -predeployment $True `
          -deleteDeployment $False }"
      shell: pwsh 